-- Provenance 層: PROV-O relation (Day 11、wasAttributedTo / wasGeneratedBy / wasDerivedFrom)
-- Q3 案 A: 3 separate structure、PROV-O 1:1 対応
-- Q4 案 A: 02-data-provenance §4.1 厳格 type (Entity × Agent / Entity × Activity / Entity × Entity)
import Init.Core
import AgentSpec.Provenance.ResearchEntity
import AgentSpec.Provenance.ResearchActivity
import AgentSpec.Provenance.ResearchAgent

/-!
# AgentSpec.Provenance.ProvRelation: PROV-O 三項 relation の Lean 化 (Day 11、A-Minimal)

Phase 0 Week 4-5 Provenance 層の Day 11 構成要素。Day 10 で **PROV-O 三項 4 type 完備**
(Verdict + ResearchEntity + ResearchActivity + ResearchAgent) を達成、Day 11 で
**3 つの主要 PROV-O relation** を Lean 化:

- `WasAttributedTo` (Entity → Agent): "entity was attributed to agent"
- `WasGeneratedBy` (Entity → Activity): "entity was generated by activity"
- `WasDerivedFrom` (Entity → Entity): "entity was derived from another entity"

これらは PROV-O Triple (RDF) に対応し、Lean では structure (record) で表現。

## 設計 (Section 2.20 Q3 案 A + Q4 案 A 確定)

    structure WasAttributedTo where
      entity : ResearchEntity
      agent : ResearchAgent

    structure WasGeneratedBy where
      entity : ResearchEntity
      activity : ResearchActivity

    structure WasDerivedFrom where
      entity : ResearchEntity
      source : ResearchEntity

3 separate structure (Q3 案 A、PROV-O 1:1 対応、TyDD-S1) で各 relation の
semantic 区別を型レベルで強制 (Q4 案 A、S4 P5 explicit assumptions)。

## DecidableEq 省略 (Day 9-10 同パターン継続)

ResearchEntity が recursive Evolution を含むため `deriving DecidableEq` 不可。
Inhabited / Repr のみ deriving、DecidableEq 手動実装は Day 12+ 検討
(Section 2.19 / 2.21 に記録)。

## TyDD 原則 (Day 1-10 確立パターン適用)

- **Pattern #5** (def Prop signature): structure 先行
- **Pattern #6** (sorry 0): structure + deriving + helper で完結
- **Pattern #7** (artifact-manifest 同 commit): Day 5 hook 化 + Day 10 v2 拡張済 (Provenance 検出可能)
- **Pattern #8** (Lean 4 予約語回避): `WasAttributedTo` / `WasGeneratedBy` / `WasDerivedFrom` は予約語ではない (PROV-O 命名規約準拠)

## Day 11 意思決定ログ

### D1. 3 separate structure 採用 (Q3 案 A、PROV-O 1:1 対応)
- **代案 B**: 1 unified inductive `ProvRelation { wasAttributedTo (e : ...) (a : ...), ... }`
- **代案 C**: 1 structure `ProvRelation { source : Entity, target : Entity, kind : RelationKind }` + enum
- **採用**: 案 A 3 separate structure
- **理由**: 02-data-provenance §4.1 PROV-O 100% 忠実 (RDF triple 1:1)、TyDD-S1 types-first、
  各 relation の semantic を型レベルで区別。案 B は variant 増加、案 C は型安全性低下。

### D2. 引数 type を PROV-O §4.1 通り厳格に (Q4 案 A)
- **代案 B**: より柔軟に Activity → Agent も許可 (overload)
- **採用**: PROV-O §4.1 通り (`WasAttributedTo : Entity × Agent` etc.)
- **理由**: TyDD-S1 + S4 P5 explicit assumptions、PROV-O semantic 厳守、案 B は overspec。

### D3. 1 ファイル統合配置 (`ProvRelation.lean`)
- **代案**: 3 separate ファイル (WasAttributedTo.lean / WasGeneratedBy.lean / WasDerivedFrom.lean)
- **採用**: 1 ファイル `ProvRelation.lean` に統合
- **理由**: 3 relation は密接に関連 (PROV-O triple)、1 ファイルで cohesion 高い、
  import 簡素化 (利用側 1 import で 3 relation 全て利用可能)。
-/

namespace AgentSpec.Provenance

/-! ### `WasAttributedTo`: Entity が Agent に帰属する関係 (PROV-O wasAttributedTo) -/

/-- 02-data-provenance §4.1 PROV-O `wasAttributedTo` (Entity → Agent)。

    "entity was attributed to agent" を表現。例: 主張 (Hypothesis) が
    研究者 (Researcher Agent) に帰属する関係。 -/
structure WasAttributedTo where
  entity : ResearchEntity
  agent : ResearchAgent
  deriving Inhabited, Repr

namespace WasAttributedTo

/-- Smart constructor: entity と agent を直接指定。 -/
def mk' (entity : ResearchEntity) (agent : ResearchAgent) : WasAttributedTo :=
  { entity := entity, agent := agent }

/-- 自明な fixture: trivial Hypothesis Entity → trivial Researcher Agent。 -/
def trivial : WasAttributedTo :=
  { entity := ResearchEntity.trivial, agent := ResearchAgent.trivial }

end WasAttributedTo

/-! ### `WasGeneratedBy`: Entity が Activity から生成された関係 (PROV-O wasGeneratedBy) -/

/-- 02-data-provenance §4.1 PROV-O `wasGeneratedBy` (Entity → Activity)。

    "entity was generated by activity" を表現。例: 主張 (Hypothesis Entity) が
    調査 activity (Investigate) によって生成された関係。 -/
structure WasGeneratedBy where
  entity : ResearchEntity
  activity : ResearchActivity
  deriving Inhabited, Repr

namespace WasGeneratedBy

/-- Smart constructor: entity と activity を直接指定。 -/
def mk' (entity : ResearchEntity) (activity : ResearchActivity) : WasGeneratedBy :=
  { entity := entity, activity := activity }

/-- 自明な fixture: trivial Hypothesis Entity ← trivial investigate activity。 -/
def trivial : WasGeneratedBy :=
  { entity := ResearchEntity.trivial, activity := ResearchActivity.trivial }

end WasGeneratedBy

/-! ### `WasDerivedFrom`: Entity が他 Entity から派生した関係 (PROV-O wasDerivedFrom) -/

/-- 02-data-provenance §4.1 PROV-O `wasDerivedFrom` (Entity → Entity)。

    "entity was derived from another entity" を表現。例: 改良された主張
    (refined Hypothesis Entity) が元の主張 (original Hypothesis Entity) から派生した関係。 -/
structure WasDerivedFrom where
  entity : ResearchEntity
  source : ResearchEntity
  deriving Inhabited, Repr

namespace WasDerivedFrom

/-- Smart constructor: entity と source を直接指定。 -/
def mk' (entity : ResearchEntity) (source : ResearchEntity) : WasDerivedFrom :=
  { entity := entity, source := source }

/-- 自明な fixture: 同一 trivial entity を source/target に。 -/
def trivial : WasDerivedFrom :=
  { entity := ResearchEntity.trivial, source := ResearchEntity.trivial }

end WasDerivedFrom

end AgentSpec.Provenance
