/-
Agent Manifesto - Empirical Postulates: E1-E2
Generated by generate-verso-source.py
-/

import VersoManual

open Verso.Genre Manual

set_option linter.verso.markup.emph false

#doc (Manual) "Empirical Postulates: E1-E2" =>

# Epistemic Layer - EmpiricalPostulate Strength 4 - E1-E2 Premise Set

Formalizes empirical postulates as Lean non-logical axioms (Terminology Reference §4.1).

## Position as Extension of T0
Procedure 2.4.

E1–E2 are "findings repeatedly demonstrated with no known counterexamples,
yet in principle refutable," constituting the extended part (Γ \ T₀) of premise set Γ.
Difference from T₀: based not on external authority (contracts, natural laws)
but on hypotheses grounded in empirical observation (Terminology Reference §9.1 empirical propositions).
They possess refutability (§9.1) and are subject to AGM contraction (§9.2).

In Lean, they are declared as `axiom` just like T₀, but each axiom card
must include a *refutation condition* (Procedure §2.5).

## Relationship to T0
Procedure 2.4.

Γ is an extension of T₀ (Terminology Reference §5.5), so Thm(T₀) ⊆ Thm(Γ).
If an E is refuted, the P's that depend on it (P1, P2) become subject to revision,
but T₀ and P's that depend solely on T₀ (P3–P6) are unaffected.
This follows from the monotonicity of extensions (§2.5 / §5.3).

## Correspondence Table


:::table +header
*
  * Axiom name
  * Corresponding E
  * Expressed property
  * Γ \ T₀ membership basis
*
  * `verification_requires_independence`
  * E1
  * Generation and evaluation must be separated
  * Hypothesis-derived
*
  * `no_self_verification`
  * E1
  * Prohibition of self-verification
  * Hypothesis-derived
*
  * `shared_bias_reduces_detection`
  * E1
  * Shared bias degrades detection power
  * Hypothesis-derived
*
  * `capability_risk_coscaling`
  * E2
  * Capability growth is inseparable from risk growth
  * Hypothesis-derived
:::


## E1 Verification Requires Independence

"Generation and evaluation by the same process has been demonstrated
  to be structurally unreliable across all domains (scientific peer review,
  financial auditing, software testing). Given T4 (probabilistic output),
  it is empirically supported that when a process with the same biases
  handles both generation and evaluation, detection power degrades."

E1 is decomposed into three axioms:
1. The agents responsible for generation and evaluation must be separated (structural independence)
2. Self-verification is not permitted (prohibition of self-verification)
3. Verification between agents sharing internal state has low detection power (bias correlation)

(Axiom Card)
   Layer: Γ \ T₀ (Hypothesis-derived)
   Content: The agents responsible for generation and evaluation must be independent.
         The agent that generated an action and the agent that verifies it
         must be distinct individuals that do not share internal state.
   Basis: A principle repeatedly demonstrated in scientific peer review,
         financial auditing, software testing, etc.
   Source: manifesto.md E1 "Verification Requires Independence"
   Refutation condition: If self-verification is demonstrated to have detection power
             equal to external verification (e.g., realization of complete self-awareness) 

*Declaration:* `axiom verification_requires_independence`

```
axiom verification_requires_independence :
  ∀ (gen ver : Agent) (action : Action) (w : World),
    generates gen action w →
    verifies ver action w →
    gen.id ≠ ver.id ∧ ¬sharesInternalState gen ver
```

(Axiom Card)
   Layer: Γ \ T₀ (Hypothesis-derived)
   Content: Prohibition of self-verification.
         The same agent cannot perform both generation and verification.
         A corollary of E1a (Terminology Reference §4.2 corollary), but declared explicitly.
   Basis: Due to T4 (probabilistic output), the bias of the same process
         affects both generation and evaluation, structurally degrading detection power.
   Source: manifesto.md E1 + Principles.lean `e1b_from_e1a` proves derivation from E1a
   Refutation condition: Same as the refutation condition for E1a 

*Declaration:* `axiom no_self_verification`

```
axiom no_self_verification :
  ∀ (agent : Agent) (action : Action) (w : World),
    generates agent action w →
    ¬verifies agent action w
```

(Axiom Card)
   Layer: Γ \ T₀ (Hypothesis-derived)
   Content: Sharing internal state correlates biases.
         Two agents sharing internal state cannot be considered independent
         verifiers, even if one generates and the other verifies.
   Basis: Detection power degradation due to shared bias is empirically
         supported by conflict-of-interest policies in scientific research,
         audit firm rotation requirements, etc.
   Source: manifesto.md E1 "When a process with the same biases handles both
           generation and evaluation, detection power degrades"
   Refutation condition: If it is demonstrated that bias correlation has no effect on detection power 

*Declaration:* `axiom shared_bias_reduces_detection`

```
axiom shared_bias_reduces_detection :
  ∀ (a b : Agent) (action : Action) (w : World),
    sharesInternalState a b →
    generates a action w →
    ¬verifies b action w
```

## E2 Capability Growth Is Inseparable from Risk Growth

"It has been repeatedly observed across all tools that capability
  enables both positive and negative outcomes. However, there is no
  proof that means to increase capability while completely containing
  risk (such as a perfect sandbox) are impossible in principle."

E2 is formalized as a single axiom.
Expansion of the action space (actionSpaceSize) necessarily entails
an increase in risk exposure (riskExposure).

## Note on Empirical Status

E2 is an empirical postulate and does not exclude the possibility
that a "perfect sandbox" may be discovered in the future. It is
assumed as an axiom, but if refuted, P1 (co-scaling of autonomy
and vulnerability) becomes subject to revision.

(Axiom Card)
   Layer: Γ \ T₀ (Hypothesis-derived)
   Content: Capability growth is inseparable from risk growth.
         When an agent's action space expands, risk exposure necessarily increases.
   Basis: It has been repeatedly observed across all tools that capability enables
         both positive and negative outcomes (Terminology Reference §9.1 empirical propositions).
   Source: manifesto.md E2 "Capability Growth Is Inseparable from Risk Growth"
   Refutation condition: If means to increase capability while completely containing risk
             are discovered (e.g., a perfect sandbox)

   *Choice of inequality: `<` vs `≤`*

   The manifesto's "inseparable" implies strict co-scaling, so
   `<` (strict increase) is adopted. If the refutation condition is met (discovery of
   a risk containment method), this axiom becomes subject to AGM contraction
   (Terminology Reference §9.2), and P1 (co-scaling of autonomy and vulnerability)
   is revised. 

*Declaration:* `axiom capability_risk_coscaling`

```
axiom capability_risk_coscaling :
  ∀ (agent : Agent) (w w' : World),
    actionSpaceSize agent w < actionSpaceSize agent w' →
    riskExposure agent w < riskExposure agent w'
```

## Sorry Inventory Phase 2 Additions


:::table +header
*
  * Location
  * Reason for sorry
*
  * `Ontology.lean: generates`
  * opaque — to be concretized as Worker actions in Phase 3+
*
  * `Ontology.lean: verifies`
  * opaque — to be concretized as Verifier actions in Phase 3+
*
  * `Ontology.lean: sharesInternalState`
  * opaque — to be concretized as session/parameter sharing in Phase 3+
*
  * `Ontology.lean: actionSpaceSize`
  * opaque — to be quantified as Observable in Phase 4+
*
  * `Ontology.lean: riskExposure`
  * opaque — to be quantified as Observable in Phase 4+
:::

