#!/usr/bin/env python3
"""
Create a GitHub issue when monitor_drift.py reports router drift.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[4]
LOG_DIR = ROOT / "docs/research/routellm-phase3/logs"
FLAG_PATH = LOG_DIR / "drift-alert.flag"


def load_report(path: Path) -> dict[str, Any]:
    with path.open() as f:
        return json.load(f)


def report_date(report: dict[str, Any], report_path: Path) -> str:
    generated_at = str(report.get("generated_at", ""))
    if generated_at:
        try:
            return datetime.fromisoformat(generated_at.replace("Z", "+00:00")).date().isoformat()
        except ValueError:
            pass

    for day in reversed(report.get("days", [])):
        if isinstance(day, str) and day:
            return day

    name = report_path.stem
    prefix = "drift-report-"
    if name.startswith(prefix):
        raw = name[len(prefix):]
        if len(raw) == 8 and raw.isdigit():
            return f"{raw[0:4]}-{raw[4:6]}-{raw[6:8]}"

    return datetime.utcnow().date().isoformat()


def load_flag(path: Path = FLAG_PATH) -> dict[str, Any] | None:
    if not path.exists():
        return None
    lines = [line for line in path.read_text().splitlines() if line.strip()]
    if not lines:
        return None
    try:
        return json.loads(lines[-1])
    except json.JSONDecodeError:
        return None


def already_alerted(date: str, flag_path: Path = FLAG_PATH) -> bool:
    flag = load_flag(flag_path)
    if not flag:
        return False
    return flag.get("alert_date") == date


def write_flag(date: str, report_path: Path, issue_url: str | None, flag_path: Path = FLAG_PATH) -> None:
    flag_path.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "alert_date": date,
        "report_path": str(report_path),
        "issue_url": issue_url,
        "created_at": datetime.utcnow().isoformat() + "Z",
    }
    flag_path.write_text(json.dumps(entry, ensure_ascii=False) + "\n")


def latest_summary(report: dict[str, Any]) -> dict[str, Any]:
    days = report.get("days") or []
    per_day = report.get("per_day") or {}
    if days:
        return per_day.get(days[-1], {})
    return {}


def pct(value: Any) -> str:
    try:
        return f"{float(value):+.1f}pt"
    except (TypeError, ValueError):
        return "n/a"


def scalar(value: Any) -> str:
    if value is None:
        return "n/a"
    return str(value)


def issue_title(report: dict[str, Any], date: str) -> str:
    drift = report.get("drift", {})
    l1 = drift.get("label_distribution_l1_pct")
    try:
        l1_text = f"{float(l1):.1f}pt"
    except (TypeError, ValueError):
        l1_text = "unknown"
    return f"[router-drift] L1 label distribution shift {l1_text} ({date})"


def issue_body(report: dict[str, Any], report_path: Path, date: str) -> str:
    drift = report.get("drift", {})
    latest = latest_summary(report)
    return "\n".join(
        [
            "## Drift Detected",
            "",
            f"**Report**: `{report_path}` (generated {date})",
            "",
            "## Metrics",
            f"- label distribution L1 distance: {scalar(drift.get('label_distribution_l1_pct'))}pt (threshold: 15pt)",
            f"- confidence mean delta: {scalar(drift.get('confidence_mean_delta'))} (threshold: +/-0.1)",
            f"- fallback pct delta: {pct(drift.get('fallback_pct_delta'))}",
            f"- n_total: {scalar(report.get('n_total'))} predictions across {len(report.get('days', []))} days",
            f"- latest day predictions: {scalar(latest.get('n'))}",
            "",
            "## Recommended Actions",
            "1. Read `docs/research/routellm-phase3/analysis/observability-runbook.md` Drift Response.",
            "2. After human approval, run `uv run python3 retrain_cli.py --base-train ... --corrections ...`.",
            "3. Confirm new model GT hold-out accuracy, then roll back if it regresses.",
            "",
            "## Reference",
            "Parent: #639 / Sub-7: #672",
            "",
            "Generated by `scripts/router-drift-check.sh` (launchd)",
        ]
    )


def create_issue(title: str, body: str) -> str:
    result = subprocess.run(
        ["gh", "issue", "create", "--label", "router-drift", "--title", title, "--body", body],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stdout, end="")
        print(result.stderr, end="", file=sys.stderr)
        raise SystemExit(result.returncode)
    return result.stdout.strip()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    report_path = args.report.resolve()
    report = load_report(report_path)
    if report.get("drift", {}).get("alert") is not True:
        print("[alert] drift.alert is not true; skip")
        return

    date = report_date(report, report_path)
    if already_alerted(date):
        print(f"[alert] already created issue for {date}")
        return

    title = issue_title(report, date)
    body = issue_body(report, report_path, date)

    if args.dry_run:
        print(title)
        print()
        print(body)
        return

    issue_url = create_issue(title, body)
    write_flag(date, report_path, issue_url)
    print(f"[alert] created {issue_url}")


if __name__ == "__main__":
    main()
