#!/usr/bin/env bash
set -uo pipefail
PASS=0; FAIL=0
BASE="$(git rev-parse --show-toplevel 2>/dev/null || echo /Users/nirarin/work/agent-manifesto)"

echo "=== Phase 3: P4 Structural Tests ==="

check() {
  local name="$1" cond="$2"
  echo -n "$name... "
  if eval "$cond"; then echo "PASS"; PASS=$((PASS+1)); else echo "FAIL"; FAIL=$((FAIL+1)); fi
}

check "S3.1 PostToolUse hook registered" \
  "jq -e '.hooks.PostToolUse | length > 0' '$BASE/.claude/settings.json' >/dev/null 2>&1"

check "S3.2 SessionStart hook registered" \
  "jq -e '.hooks.SessionStart | length > 0' '$BASE/.claude/settings.json' >/dev/null 2>&1"

check "S3.3 Metrics collector hook exists" \
  "[ -x '$BASE/.claude/hooks/p4-metrics-collector.sh' ]"

check "S3.4 Gate logger hook exists" \
  "[ -x '$BASE/.claude/hooks/p4-gate-logger.sh' ]"

check "S3.5 Metrics skill exists" \
  "[ -f '$BASE/.claude/skills/metrics/SKILL.md' ]"

check "S3.6 Metrics directory exists" \
  "[ -d '$BASE/.claude/metrics' ]"

check "S3.7 PostToolUse hook is async (non-blocking)" \
  "jq -e '.hooks.PostToolUse[0].hooks[0].async == true' '$BASE/.claude/settings.json' >/dev/null 2>&1"

check "S3.8 Metrics collector logs to JSONL" \
  "grep -q 'jsonl' '$BASE/.claude/hooks/p4-metrics-collector.sh'"

check "S3.9 Metrics skill covers V1-V7" \
  "grep -c 'V[1-7]' '$BASE/.claude/skills/metrics/SKILL.md' | xargs test 7 -le"

check "S3.25 h5-doc-lint hook exists and is executable" \
  "[ -x '$BASE/.claude/hooks/h5-doc-lint.sh' ]"

check "S3.26 p3-axiom-evidence-check hook exists and is executable" \
  "[ -x '$BASE/.claude/hooks/p3-axiom-evidence-check.sh' ]"

check "S3.27 p4-sync-counts-check hook exists and is executable" \
  "[ -x '$BASE/.claude/hooks/p4-sync-counts-check.sh' ]"

echo ""
echo "=== Phase 3: Plugin Drift Tests ==="

DIST="$BASE/dist/agent-manifesto-plugin"

# S3.10: dist/ is auto-generated by /package-plugin and gitignored.
# When absent, drift tests are not applicable. (#432)
if [ -d "$DIST" ]; then
  echo "S3.10 Plugin dist directory exists... PASS"
  PASS=$((PASS+1))

  check "S3.11 l1-safety-check.sh in dist" \
    "[ -f '$DIST/hooks/l1-safety-check.sh' ]"

  check "S3.12 p3-compatibility-check.sh in dist" \
    "[ -f '$DIST/hooks/p3-compatibility-check.sh' ]"

  check "S3.13 p4-metrics-collector.sh in dist" \
    "[ -f '$DIST/hooks/p4-metrics-collector.sh' ]"

  check "S3.14 evolve-metrics-recorder.sh excluded from dist" \
    "[ ! -f '$DIST/hooks/evolve-metrics-recorder.sh' ]"

  check "S3.15 evolve-state-loader.sh excluded from dist" \
    "[ ! -f '$DIST/hooks/evolve-state-loader.sh' ]"

  check "S3.16 hypothesizer agent excluded from dist" \
    "[ ! -d '$DIST/agents/hypothesizer' ]"

  check "S3.17 integrator agent excluded from dist" \
    "[ ! -d '$DIST/agents/integrator' ]"

  check "S3.18 observer agent excluded from dist" \
    "[ ! -d '$DIST/agents/observer' ]"

  check "S3.19 evolve skill excluded from dist" \
    "[ ! -d '$DIST/skills/evolve' ]"

  check "S3.20 l1-safety-check.sh dist/src content matches" \
    "diff -q '$BASE/.claude/hooks/l1-safety-check.sh' '$DIST/hooks/l1-safety-check.sh' >/dev/null 2>&1"

  check "S3.21 p3-compatibility-check.sh dist/src content matches" \
    "diff -q '$BASE/.claude/hooks/p3-compatibility-check.sh' '$DIST/hooks/p3-compatibility-check.sh' >/dev/null 2>&1"

  check "S3.22 p4-metrics-collector.sh dist/src content matches" \
    "diff -q '$BASE/.claude/hooks/p4-metrics-collector.sh' '$DIST/hooks/p4-metrics-collector.sh' >/dev/null 2>&1"

  check "S3.23 plugin.json is valid JSON" \
    "jq . '$DIST/plugin.json' >/dev/null 2>&1"

  check "S3.24 hooks.json is valid JSON" \
    "jq . '$DIST/hooks/hooks.json' >/dev/null 2>&1"
else
  echo "S3.10 Plugin dist not present (auto-generated, gitignored)... N/A"
fi

echo ""
echo "=== Results: $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
