#!/usr/bin/env bash
# scripts/update-handoff.sh — handoff-resume-research-new-foundation.md を current state に再生成
# Day 78 N1 [Gap A] (Day 73 PC-crash incident 構造的解消)
#
# Usage:
#   bash scripts/update-handoff.sh
#
# 動作:
#   1. 現在の HEAD sha + branch + 最新 day_plan entry 取得
#   2. lake build state + cycle-check 結果 取得
#   3. 主 repo の .claude/handoffs/handoff-resume-research-new-foundation.md を再生成
#
# 終了コード:
#   0  成功
#   1  jq error or git error

set -u
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
MANIFEST="$REPO_ROOT/agent-spec-lib/artifact-manifest.json"
PENDING="$REPO_ROOT/docs/research/new-foundation-survey/11-pending-tasks.json"

# 主 repo path: research/new-foundation worktree → ~/work/agent-manifesto/.claude/handoffs/
MAIN_REPO="${MAIN_REPO:-/Users/nirarin/work/agent-manifesto}"
HANDOFF_FILE="$MAIN_REPO/.claude/handoffs/handoff-resume-research-new-foundation.md"

if [ ! -d "$(dirname "$HANDOFF_FILE")" ]; then
  echo "ERROR: handoff dir not found: $(dirname "$HANDOFF_FILE")" >&2
  exit 1
fi

# Step 1: state 取得
HEAD_SHA=$(git -C "$REPO_ROOT" rev-parse HEAD)
BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)

# 最新 done day_plan entry (Check 2 と同じ pattern: 整数部正規化 sort)
LATEST_DAY=$(jq -r '
  [.day_plan[] | select(.status == "done") | .day
   | if type == "number" then . else (split(".") | .[0] | tonumber) end]
  | sort | .[-1] // 0
' "$PENDING")
LATEST_SCOPE=$(jq -r --argjson d "$LATEST_DAY" '
  [.day_plan[] | select(.status == "done" and (.day | if type == "number" then . else (split(".") | .[0] | tonumber) end) == $d)]
  | .[0].scope // ""
' "$PENDING")

EXAMPLE_COUNT=$(jq -r '.build_status.example_count' "$MANIFEST")
THEOREM_COUNT=$(jq -r '.build_status.theorem_count' "$MANIFEST")
AXIOM_COUNT=$(jq -r '.build_status.axiom_count' "$MANIFEST")
SORRY_COUNT=$(jq -r '.build_status.sorry_count' "$MANIFEST")
VERSION=$(jq -r '.version' "$MANIFEST")

# 7-day empirical: last empirical date
LAST_EMP=$(jq -r '[.verifier_history[] | select(.round | test("Empirical"))] | .[-1].date // "unknown"' "$MANIFEST")
LAST_EMP_ROUND=$(jq -r '[.verifier_history[] | select(.round | test("Empirical"))] | .[-1].round // "unknown"' "$MANIFEST")

# 次の empirical: last + 7 day
if date -ju -f "%Y-%m-%d" "$LAST_EMP" "+%s" >/dev/null 2>&1; then
  NEXT_EMP_EPOCH=$(($(date -ju -f "%Y-%m-%d" "$LAST_EMP" "+%s") + 7 * 86400))
  NEXT_EMP=$(date -ju -f "%s" "$NEXT_EMP_EPOCH" "+%Y-%m-%d")
else
  NEXT_EMP_EPOCH=$(($(date -u -d "$LAST_EMP" "+%s") + 7 * 86400))
  NEXT_EMP=$(date -u -d "@$NEXT_EMP_EPOCH" "+%Y-%m-%d")
fi

# pending priority: 🔴 / 🟡 件数
PENDING_RED=$(jq -r '[.pending_items[] | select(.status == "pending" and .mark == "🔴")] | length' "$PENDING")
PENDING_YELLOW=$(jq -r '[.pending_items[] | select(.status == "pending" and .mark == "🟡")] | length' "$PENDING")

# Step 2: handoff file 再生成
cat > "$HANDOFF_FILE" <<EOF
# Handoff Resume
git_sha: $HEAD_SHA
branch: $BRANCH
worktree: $REPO_ROOT
skill: agent-spec-lib Day N cycle (custom workflow、9 step、auto mode)
phase: Week 3 Day $LATEST_DAY 完了、Day $((LATEST_DAY + 1)) 着手前
intent: agent-manifesto-new-foundation worktree で Phase 0 Week 3 Day-by-Day cycle を進める。Spine 層 + Manifest 移植 + GA-S Lattice、empirical 7-day cycle で drift 検証、cycle-check.sh で構造的再発防止。auto mode (人間判断必要時のみ pause)。

## Latest state (auto-generated by scripts/update-handoff.sh)

### Done at Day $LATEST_DAY
$LATEST_SCOPE

### Build state (HEAD = $HEAD_SHA)
- artifact-manifest version: $VERSION
- example_count: $EXAMPLE_COUNT
- theorem_count: $THEOREM_COUNT
- axiom_count: $AXIOM_COUNT
- sorry_count: $SORRY_COUNT
- last empirical: $LAST_EMP ($LAST_EMP_ROUND)
- next empirical scheduled: $NEXT_EMP

### Pending priority
- 🔴 high: $PENDING_RED 件
- 🟡 medium: $PENDING_YELLOW 件

## Resume 手順

1. \`cd $REPO_ROOT\`
2. \`bash scripts/cycle-check.sh\` で current state 確認 (Check 12 = 9/9 期待)
3. \`jq '.day_plan[-3:]' $PENDING\` で直近 3 Day の scope 確認
4. \`jq '.pending_items[] | select(.mark == "🔴")' $PENDING\` で 🔴 priority 列挙
5. Day $((LATEST_DAY + 1)) 着手 — 9-step cycle (paper survey → impl → TyDD → impl → metadata → docs → やり残し → Day N+1 議論 → 最終後続)

## Key files

1. **artifact-manifest**: \`agent-spec-lib/artifact-manifest.json\` (verifier_history + build_status + breakdown)
2. **pending tasks**: \`docs/research/new-foundation-survey/11-pending-tasks.json\` (day_plan + pending_items + roadmap + gap_analysis)
3. **9-step cycle 規律**: \`~/.claude/projects/-Users-nirarin-work-agent-manifesto/memory/project_day_cycle_pattern.md\`
4. **CLAUDE.md**: \`~/.claude/CLAUDE.md\` (TyDD+TDD, Cycle Task script 化, Linter vs Skill 分離)

## Day N 完了時の routine

\`\`\`bash
# 1. metadata (artifact-manifest version + verifier_history append + day_plan)
# 2. cycle-check
bash scripts/cycle-check.sh
# 3. git commit (feat or chore、conservative/compatible/breaking 分類明記)
# 4. metadata-only commit (commit hash backfill)
bash scripts/backfill-day-commit.sh \$DAY \$COMMIT_HASH
# 5. handoff 更新
bash scripts/update-handoff.sh
\`\`\`
EOF

echo "OK: handoff updated at $HANDOFF_FILE (Day $LATEST_DAY, HEAD=$HEAD_SHA)" >&2
exit 0
