import Manifest.Ontology
import Manifest.Models.EpistemicLayer

/-!
# Safety Enforcement Plugin — Conditional Assumptions

Auto-generated by D17 self-dialogue protocol (G3 experiment, #287).
All assumptions are H-type (LLM inference). No C-type (human decision).

## Source
- G1 Observer: Source 5 (Cross-Project Patterns)
- D17 Step 1 (extract): Vision Answerer self-dialogue
- extractStepValid: PASS (12 H-type, 0 missing TemporalValidity)
-/

namespace Manifest.Models.Instances.SafetyPlugin

open Manifest

-- ============================================================
-- Assumption type (simplified for this instance)
-- ============================================================

structure PluginAssumption where
  id : String
  content : String
  sourceRef : String
  reviewIntervalDays : Nat
  deriving Repr

-- ============================================================
-- H-type assumptions (LLM inference)
-- ============================================================

/-- SEP-H1: PreToolUse hooks are the only reliable enforcement mechanism.
    Deny rules are bypassable via indirect execution (PoC 3). -/
def sep_h1 : PluginAssumption := {
  id := "SEP-H1"
  content := "PreToolUse hooks are the only reliable mechanism for blocking unsafe tool execution"
  sourceRef := "agent-manifesto PoC 3, CC-H1"
  reviewIntervalDays := 60
}

/-- SEP-H2: Plugin hooks merge with host hooks via parallel execution.
    Conflict resolution: deny > defer > ask > allow. -/
def sep_h2 : PluginAssumption := {
  id := "SEP-H2"
  content := "Plugin hooks merge via parallel execution with deny-wins priority"
  sourceRef := "CC-H6, PD-14"
  reviewIntervalDays := 60
}

/-- SEP-H4: jq is required. Without it, hooks fail silently (PD-71 fail-open). -/
def sep_h4 : PluginAssumption := {
  id := "SEP-H4"
  content := "jq is available on target systems; without it, zero enforcement"
  sourceRef := "PD-71, l1-safety-check.sh"
  reviewIntervalDays := 90
}

/-- SEP-H9: POSIX shell utilities suffice for cross-platform portability. -/
def sep_h9 : PluginAssumption := {
  id := "SEP-H9"
  content := "POSIX shell utilities (grep -qE, sed) suffice for macOS + Linux"
  sourceRef := "CLAUDE.md grep -oP gotcha"
  reviewIntervalDays := 180
}

/-- SEP-H3: CLAUDE_PLUGIN_ROOT enables portable hook script paths. -/
def sep_h3 : PluginAssumption := {
  id := "SEP-H3"
  content := "CLAUDE_PLUGIN_ROOT paths in hooks.json are resolved at runtime"
  sourceRef := "claude-code-technical-spec.md section I.4"
  reviewIntervalDays := 90
}

/-- SEP-H5: Fixed regex patterns achieve low false positive rate. -/
def sep_h5 : PluginAssumption := {
  id := "SEP-H5"
  content := "Fixed regex patterns for destructive commands achieve acceptable false positive rate"
  sourceRef := "l1-safety-check.sh patterns, 98 evolve runs"
  reviewIntervalDays := 90
}

/-- SEP-H6: Filename-based secret detection is sufficient. -/
def sep_h6 : PluginAssumption := {
  id := "SEP-H6"
  content := "Filename patterns (env, pem, key, credentials) detect secrets without content inspection"
  sourceRef := "l1-safety-check.sh secret patterns"
  reviewIntervalDays := 90
}

/-- SEP-H7: Test tampering detection via disable-keywords works cross-framework. -/
def sep_h7 : PluginAssumption := {
  id := "SEP-H7"
  content := "Disable-keyword detection works across test frameworks (Jest, Mocha, RSpec, pytest)"
  sourceRef := "l1-file-guard.sh test patterns"
  reviewIntervalDays := 90
}

/-- SEP-H8: Plugin can protect own scripts via file guard on PLUGIN_ROOT. -/
def sep_h8 : PluginAssumption := {
  id := "SEP-H8"
  content := "File guard blocking Edit/Write to CLAUDE_PLUGIN_ROOT achieves self-protection"
  sourceRef := "l1-file-guard.sh hook self-protection"
  reviewIntervalDays := 90
}

/-- SEP-H10: Blocked events must be logged from PreToolUse (PostToolUse never fires). -/
def sep_h10 : PluginAssumption := {
  id := "SEP-H10"
  content := "PostToolUse never fires for blocked tools; audit logging must be in PreToolUse"
  sourceRef := "l1-safety-check.sh log_gate_blocked, CC-H5"
  reviewIntervalDays := 60
}

/-- SEP-H11: Zero-config installation is achievable with fixed universal patterns. -/
def sep_h11 : PluginAssumption := {
  id := "SEP-H11"
  content := "Fixed universal safety patterns enable zero-config installation"
  sourceRef := "Vision document, l1-safety-check.sh"
  reviewIntervalDays := 90
}

/-- SEP-H12: Hook stdin JSON schema is stable across Claude Code versions. -/
def sep_h12 : PluginAssumption := {
  id := "SEP-H12"
  content := "Hook stdin JSON schema (tool_input.command, tool_input.file_path) is stable"
  sourceRef := "claude-code-technical-spec.md section A.2"
  reviewIntervalDays := 60
}

def allAssumptions : List PluginAssumption :=
  [sep_h1, sep_h2, sep_h3, sep_h4, sep_h5, sep_h6, sep_h7, sep_h8, sep_h9, sep_h10, sep_h11, sep_h12]

end Manifest.Models.Instances.SafetyPlugin
