import Manifest.DesignFoundation
import Manifest.Models.Instances.SafetyPlugin.Assumptions

/-!
# Safety Enforcement Plugin - Conditional Design Foundation

Auto-generated by D17 self-dialogue protocol (G3 experiment, #287).

Derives plugin-specific axioms from the base manifesto (T₀) and
the SEP-H assumptions extracted in Step 1.

## D17 Step 2 - Conditional Axiom System

This file constitutes the conditional axiom system for the safety plugin:
T₀ ∪ {SEP-H1, ..., SEP-H12} ⊢ SEP-axioms
-/

namespace Manifest.Models.Instances.SafetyPlugin

open Manifest

-- ============================================================
-- Plugin-specific primitives
-- ============================================================

/-- Safety enforcement mechanisms available in a Claude Code plugin. -/
inductive SafetyPrimitive where
  | bashGuard         -- PreToolUse:Bash hook for destructive command blocking
  | fileGuard         -- PreToolUse:Edit/Write hook for file protection
  | secretDetector    -- Pattern-based secret file detection
  | testTamperGuard   -- Test disable-keyword detection
  | selfProtection    -- Plugin script self-protection
  | auditLogger       -- Gate-blocked event logging
  deriving BEq, Repr

-- ============================================================
-- SEP Axiom 1: Hook-based enforcement is primary (from SEP-H1)
--
-- D1 maps enforcement layers. In the plugin context:
--   structural = PreToolUse hooks (can block)
--   procedural = PostToolUse hooks (can observe, not block)
--   normative  = CLAUDE.md recommendations (may be ignored)
-- ============================================================

/-- Plugin enforcement layer mapping (D1 instance).
    SEP-H1: only PreToolUse hooks reliably block. -/
def pluginEnforcementLayer : SafetyPrimitive → EnforcementLayer
  | .bashGuard       => .structural   -- PreToolUse:Bash, exit 2 blocks
  | .fileGuard       => .structural   -- PreToolUse:Edit/Write, exit 2 blocks
  | .secretDetector  => .structural   -- Part of bashGuard (git add interception)
  | .testTamperGuard => .structural   -- Part of fileGuard (edit interception)
  | .selfProtection  => .structural   -- Part of fileGuard (path guard)
  | .auditLogger     => .procedural   -- PreToolUse logging (not PostToolUse, per SEP-H10)

/-- SEP Axiom 1: All safety-critical primitives use structural enforcement.
    Derives from: SEP-H1 (hooks are only reliable mechanism) + D1 (layering). -/
theorem sep_all_safety_structural :
  ∀ p : SafetyPrimitive,
    p ≠ .auditLogger →
    pluginEnforcementLayer p = .structural := by
  intro p hp
  cases p <;> simp [pluginEnforcementLayer] <;> contradiction

-- ============================================================
-- SEP Axiom 2: Deny-wins conflict resolution (from SEP-H2)
-- ============================================================

/-- Conflict resolution priority for hook decisions.
    SEP-H2: deny > defer > ask > allow.
    This means a plugin's deny cannot be overridden by a project's allow. -/
inductive HookDecision where
  | allow | ask | defer | deny
  deriving BEq, Repr

def HookDecision.priority : HookDecision → Nat
  | .allow => 0
  | .ask   => 1
  | .defer => 2
  | .deny  => 3

/-- SEP Axiom 2: Deny always wins in conflict resolution.
    Derives from: SEP-H2 (parallel merge with deny-wins). -/
theorem sep_deny_wins :
  ∀ d : HookDecision, HookDecision.priority .deny ≥ HookDecision.priority d := by
  intro d; cases d <;> simp [HookDecision.priority]

-- ============================================================
-- SEP Axiom 3: Audit must be in-band (from SEP-H10)
-- ============================================================

/-- Where blocked events are logged.
    SEP-H10: PostToolUse never fires for blocked tools.
    Therefore audit logging must happen inside PreToolUse. -/
inductive AuditLocation where
  | preToolUse   -- Log from within the blocking hook (reliable)
  | postToolUse  -- Log from PostToolUse (unreliable for blocked events)

/-- SEP Axiom 3: Blocked event logging must use PreToolUse, not PostToolUse.
    Derives from: SEP-H10 (PostToolUse never fires for blocked tools). -/
def auditForBlockedEvents : AuditLocation := .preToolUse

-- ============================================================
-- SEP Axiom 4: Cross-platform portability (from SEP-H9)
-- ============================================================

/-- Shell feature categories by portability level.
    SEP-H9: POSIX utilities suffice. -/
inductive ShellFeature where
  | posix      -- grep -qE, sed, basename (portable)
  | gnuOnly    -- grep -oP, sed -i'' (non-portable)
  deriving BEq, Repr

/-- SEP Axiom 4: Plugin hooks must use only POSIX features.
    Derives from: SEP-H9 (cross-platform requirement). -/
def pluginShellRequirement : ShellFeature := .posix

-- ============================================================
-- Composite theorem: Plugin safety properties
-- ============================================================

/-- The plugin's safety model: all enforcement is structural,
    deny decisions cannot be overridden, and audit is in-band. -/
theorem sep_safety_model :
  pluginEnforcementLayer .bashGuard = .structural ∧
  pluginEnforcementLayer .fileGuard = .structural ∧
  HookDecision.priority .deny ≥ HookDecision.priority .allow ∧
  auditForBlockedEvents = .preToolUse := by
  exact ⟨rfl, rfl, by simp [HookDecision.priority], rfl⟩

end Manifest.Models.Instances.SafetyPlugin
